# Basic set up for three package managers

version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/themes/thecodeboss/"
    schedule:
      interval: "weekly"
    # Disable version updates for npm dependencies.
    # NOTE: When Dependabot supports grouped updates, remove this.
    open-pull-requests-limit: 0

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/docker/prod/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
