languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'thecodeboss'
googleAnalytics = 'G-WH3CEERYQX'

[permalinks]
  entry = '/:year/:month/:title/'

[markup.goldmark.renderer]
  unsafe= true

[params]
  dateFormat = "02 Jan 2006"
  logo = 'https://personal-k8s-main-space.nyc3.cdn.digitaloceanspaces.com/thecodeboss.dev/global/logo/logo.png'
  profile = 'https://personal-k8s-main-space.nyc3.cdn.digitaloceanspaces.com/thecodeboss.dev/pages/home/2023-profile-optimized.jpeg'
  title = "Aaron Krauss | Developer"
  description = "Hi, I'm Aaron Krauss, and I'm a software developer based in Oklahoma City, OK, currently working at Clevyr."
  images = [
    'https://personal-k8s-main-space.nyc3.cdn.digitaloceanspaces.com/thecodeboss.dev/global/opengraph/opengraph.jpg'
  ]

[menu]
[[menu.social]]
  identifier = 'github'
  name = 'My GitHub'
  url = 'https://github.com/alkrauss48'
  weight = 1
[[menu.social]]
  identifier = 'linked-in'
  name = 'My LinkedIn'
  url = 'https://www.linkedin.com/in/alkrauss48/'
  weight = 2
[[menu.social]]
  identifier = 'meetup'
  name = 'OKC WebDevs Meetup'
  url = 'https://www.meetup.com/okcwebdevs/'
  weight = 3

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'solarized-light'
    tabWidth = 4
