version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    # image: alkrauss48/thecodeboss-hugo:dev-main
    platform: linux/amd64
    ports:
      - "1313:80"
