name: ci

on: push

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./themes/thecodeboss
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache frontend dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install npm dependencies
        run: npm ci --prefer-offline
      - name: Frontend Lint
        run: npm run lint:js
  stylelint:
    name: Stylelint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./themes/thecodeboss
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache frontend dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install npm dependencies
        run: npm ci --prefer-offline
      - name: Frontend Lint
        run: npm run lint:css
  build:
    name: Build Image
    needs: ['eslint', 'stylelint']
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: alkrauss48/thecodeboss-hugo
          tags: |
            type=ref,prefix=dev-,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/prod/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
